n = int(input("Digite um numero: "))
print("{} x 0 eh = {}".format(n, n*0))
print("{} x 1 eh = {}".format(n, n*1))
print("{} x 2 eh = {}".format(n, n*2))
print("{} x 3 eh = {}".format(n, n*3))
print("{} x 4 eh = {}".format(n, n*4))
print("{} x 5 eh = {}".format(n, n*5))
print("{} x 6 eh = {}".format(n, n*6))
print("{} x 7 eh = {}".format(n, n*7))
print("{} x 8 eh = {}".format(n, n*8))
print("{} x 9 eh = {}".format(n, n*9))
print("{} x 10 eh = {}".format(n, n*10))

